# File: Counting DNA Nucleotides

DNA = "TGAAAATAGGCAAGGTTCGGTGTCTCTGACCCTATTATAAGGAGCTCGACCGCCATGCGCGACCTCGGGTTAGCACACCCCAATTCGTCCTAAGACCAATTCAGGATGAGACTGACATGTATGCAACGCAGGAAACGAGCTGTCGTTAAGACGTCGAGTTTTCTGTACTAGCTCACCACGCACAAACGTGTGGTTCAATCTGTACACAATCTTCTGGCGTATACAGTGAATGTCGGCTTACACCGCAGGACCTTATCATTAGCCTTAACGTGGGCTTGGGTGCACCACTGTAGTGTCAGTGGTTATACCGCAGAATGTAATTGCTGGTGAGCGCACTCCCTTTTGACTGATTAGGGACGTGAATCAGCATGAGGTGCTTAAGCTTTCCCGTCACAGCAAATCAGAAAACGCTACACACATCCCTCCGGTCAGGCCCAGCAGTCAAATTCTTCAAAGTTCAAGGTCCGTATCCCCGTGAGGATAATGCCCGCAGAGCGATTTGACTGGTCCATACAAAGTCGGTCGACAAGCAGGCGGAATATGGTCCATCAGGCATGCCTTTGGTGACAAGAGTCTTAGGTCGCCACTGAGGTAACGATAGCCGGATCCTAAGCCCCCCTCGCTACCACGGAACCACGCTAGCTAGTATACTAACCAAGAACCCAACGTGACAGACAACCACTGTGAGAGAAAATTAAGTTACCTGTCCGTCATCGTTAAATTCGATGGTCTTGGTACGGACTCATTATCCAGGCTAGCCCTTACGTTCTACATACAGTCACCGCCAGTCTTTCAGCCTTCAGGCGTGTGACTAGGG"

Acount = 0
Ccount = 0
Gcount = 0
Tcount = 0

for index in DNA:
    if index == 'A':
        Acount+=1
    elif index == 'C':
        Ccount+=1
    elif index == 'G':
        Gcount+=1
    else:
        Tcount+=1

print str(Acount) + ' ' + str(Ccount) + ' ' + str(Gcount) + ' ' + str(Tcount)

        
